#include "NoteOutput.h"
#include "FIO.h"
#include "Timer.h"

/* Usage Guideline
 * call SetChInterval to change the note frequency
 * call enableCh to play the note
 * call disableCh to stop playing the note
 * Implement the togglePin functions to use whichever IOpin as the square wave output.
 * 
 * For now the only outputs are square waves generated by timed interrupts.
 * Square waves are 50% duty cycle
 * 
 */

#define ISER0 (*(volatile unsigned int *) 0xE000E100)
#define PSEL0 (*(volatile unsigned int *) 0x400FC1A8)

void initNoteSystem(void){
	PSEL0 |= (1 << 2);	  //PCLK = CCLK
    T0.IR = 0xF;          //Clear MR Interupt flags
    T0.TCR |= 1;          //Enable Timer0 counter
    ISER0 = (1 << 1);     //Enable Timer0 interrupts

	//Set P0.23, P0.24, P0.25, P0.26 as outputs and set no pull resistors
	FIO[0].DIR |= (0xF << 23);
	PINMODE[1] |= (0xAA << 14);
}

/* Contains the time intervals for each Match Register
 * This is used to update the Match Register during the interrupt handler for the next interrupt.
 * To achieve an output at a frequency f the interval value is
 * Value = PCLK / (2f)
 */
unsigned int ChInterval[4];

// Enables interrupt generation from the specified match register
void enableCh(int MR){
	T0.MCR |= (1 << 3*MR);
    T0.MR[MR] = T0.TC + ChInterval[MR];
}

// Changes the interval for the Match Register
void setChInterval(int MR, unsigned int interval){
    ChInterval[MR] = interval;
}

/* Disables interrupt generation from the specified Match Register.
 * Also clears the relevant interrupt flag.
 */
void disableCh(int MR){
    T0.IR = (1 << MR);
    T0.MCR &= ~(1 << 3*MR);
}

int pinState [] = {1, 1, 1, 1};
void togglePin0(){
	if (pinState[0])
		FIO[0].SET |= (1 << 23);
	else
		FIO[0].CLR |= (1 << 23);
	pinState[0] = !pinState[0];
}
void togglePin1(){
	if (pinState[1])
		FIO[0].SET |= (1 << 24);
	else
		FIO[0].CLR |= (1 << 24);
	pinState[1] = !pinState[1];
}
void togglePin2(){
	if (pinState[2])
		FIO[0].SET |= (1 << 25);
	else
		FIO[0].CLR |= (1 << 25);
	pinState[2] = !pinState[2];
}
void togglePin3(){
	if (pinState[3])
		FIO[0].SET |= (1 << 26);
	else
		FIO[0].CLR |= (1 << 26);
	pinState[3] = !pinState[3];
}

void TIMER0_IRQHandler(void){
    if (T0.IR & 1){
        T0.IR = 1;
        T0.MR[0] += ChInterval[0];
        togglePin0();
    }
    if (T0.IR & 2){
        T0.IR = 2;
        T0.MR[1] += ChInterval[1];
        togglePin1();
    }
    if (T0.IR & 4){
        T0.IR = 4;
        T0.MR[2] += ChInterval[2];
        togglePin2();
    }
    if (T0.IR & 8){
        T0.IR = 8;
        T0.MR[3] += ChInterval[3];
        togglePin3();
    }
}
